import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const ROOT=path.join(__dirname,'public');
const PORT=Number(process.env.PORT||4173);
const rooms=new Map(); let clientSeq=1;
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'};

function sendFile(req,res){let url=new URL(req.url,'http://localhost').pathname;if(url==='/')url='/index.html';const fp=path.normalize(path.join(ROOT,url));if(!fp.startsWith(ROOT)){res.writeHead(403);return res.end('forbidden')}fs.readFile(fp,(err,data)=>{if(err){res.writeHead(404);return res.end('not found')}res.writeHead(200,{'content-type':MIME[path.extname(fp)]||'application/octet-stream','cache-control':'no-cache'});res.end(data)})}
const server=http.createServer((req,res)=>{
 if(req.url.startsWith('/api/health')){res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({ok:true,version:'0.4.0',mode:'TDM',scoreLimit:40,rooms:rooms.size,players:[...rooms.values()].reduce((n,r)=>n+r.players.size,0),tickRate:30}))}
 if(req.url.startsWith('/api/leaderboard')){res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify([...rooms.values()].flatMap(r=>[...r.players.values()].map(p=>({name:p.name,k:p.kills,d:p.deaths,team:p.team}))).sort((a,b)=>b.k-a.k).slice(0,50)))}
 sendFile(req,res)
});

function wsAccept(key){return crypto.createHash('sha1').update(key+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64')}
function frameText(str){const data=Buffer.from(str);let head;if(data.length<126){head=Buffer.alloc(2);head[0]=0x81;head[1]=data.length}else if(data.length<65536){head=Buffer.alloc(4);head[0]=0x81;head[1]=126;head.writeUInt16BE(data.length,2)}else{head=Buffer.alloc(10);head[0]=0x81;head[1]=127;head.writeBigUInt64BE(BigInt(data.length),2)}return Buffer.concat([head,data])}
function decodeFrames(buf){const out=[];let o=0;while(o+2<=buf.length){const b0=buf[o],b1=buf[o+1],opcode=b0&15,masked=!!(b1&128);let len=b1&127,header=2;if(len===126){if(o+4>buf.length)break;len=buf.readUInt16BE(o+2);header=4}else if(len===127){if(o+10>buf.length)break;len=Number(buf.readBigUInt64BE(o+2));header=10}const maskLen=masked?4:0;if(o+header+maskLen+len>buf.length)break;let start=o+header;let mask;if(masked){mask=buf.subarray(start,start+4);start+=4}const payload=Buffer.from(buf.subarray(start,start+len));if(masked)for(let i=0;i<payload.length;i++)payload[i]^=mask[i%4];out.push({opcode,payload});o=start+len}return {frames:out,rest:buf.subarray(o)}}
function send(sock,obj){if(sock.destroyed)return;try{sock.write(frameText(JSON.stringify(obj)))}catch{}}
function pickRoom(){for(const r of rooms.values())if(r.players.size<6)return r;const id=crypto.randomBytes(3).toString('hex');const r={id,players:new Map(),created:Date.now()};rooms.set(id,r);return r}
function sanitizeState(p,m,now){if(!Array.isArray(m.p)||m.p.length!==3)return;const nx=Math.max(-31,Math.min(31,Number(m.p[0])||0)),ny=Math.max(.8,Math.min(12,Number(m.p[1])||1.75)),nz=Math.max(-31,Math.min(31,Number(m.p[2])||0));const dt=Math.max(.016,(now-p.lastState)/1000);const dx=nx-p.p[0],dy=ny-p.p[1],dz=nz-p.p[2],dist=Math.hypot(dx,dy,dz);const max=15*dt+1.2;if(dist>max){const k=max/dist;p.p[0]+=dx*k;p.p[1]+=dy*k;p.p[2]+=dz*k}else p.p=[nx,ny,nz];p.y=Number(m.y)||0;p.lastState=now}
function shot(room,p,m,now){const cooldown=[85,550,820][m.w|0]||100;if(now-p.lastShot<cooldown)return;p.lastShot=now;if(!Array.isArray(m.o)||!Array.isArray(m.d))return;const o=m.o.map(Number),d=m.d.map(Number);const dl=Math.hypot(...d)||1;for(let i=0;i<3;i++)d[i]/=dl;let best=null,bt=1e9;for(const q of room.players.values()){if(q.id===p.id||q.team===p.team||q.dead)continue;const cx=q.p[0]-o[0],cy=q.p[1]-o[1],cz=q.p[2]-o[2],t=cx*d[0]+cy*d[1]+cz*d[2];if(t<0||t>120)continue;const hitY=Math.max(q.p[1]-.85,Math.min(q.p[1]+.9,o[1]+d[1]*t));const px=o[0]+d[0]*t-q.p[0],py=o[1]+d[1]*t-hitY,pz=o[2]+d[2]*t-q.p[2];if(Math.hypot(px,py,pz)<.68&&t<bt){best=q;bt=t}}if(best){const dmg=[24,14,92][m.w|0]||20;best.health-=dmg;if(best.health<=0){best.health=100;best.deaths++;p.kills++;best.p=[best.team===0?-7:7,1.75,best.team===0?25.5:-25.5];for(const q of room.players.values())send(q.sock,{t:'kill',killer:p.name,victim:best.name})}}}
server.on('upgrade',(req,socket)=>{if(req.url!='/ws'){socket.destroy();return}const key=req.headers['sec-websocket-key'];if(!key){socket.destroy();return}socket.write('HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: '+wsAccept(key)+'\r\n\r\n');const room=pickRoom();const id=String(clientSeq++),team=[...room.players.values()].filter(x=>x.team===0).length<3?0:1;const p={id,sock:socket,name:'PLAYER '+id,team,p:[team===0?0:0,1.75,team===0?25.5:-25.5],y:0,health:100,kills:0,deaths:0,lastState:Date.now(),lastShot:0,buf:Buffer.alloc(0)};room.players.set(id,p);send(socket,{t:'welcome',id,room:room.id,team,tickRate:30});socket.on('data',chunk=>{p.buf=Buffer.concat([p.buf,chunk]);const dec=decodeFrames(p.buf);p.buf=dec.rest;for(const f of dec.frames){if(f.opcode===8){socket.end();continue}if(f.opcode===9){socket.write(Buffer.from([0x8A,0x00]));continue}if(f.opcode!==1)continue;let m;try{m=JSON.parse(f.payload.toString('utf8'))}catch{continue}const now=Date.now();if(m.t==='hello'&&typeof m.name==='string')p.name=m.name.replace(/[^a-z0-9 _-]/gi,'').slice(0,18)||p.name;else if(m.t==='state')sanitizeState(p,m,now);else if(m.t==='shot')shot(room,p,m,now)}});const cleanup=()=>{room.players.delete(id);if(!room.players.size)rooms.delete(room.id)};socket.on('close',cleanup);socket.on('error',cleanup)});
setInterval(()=>{for(const room of rooms.values()){const players=[...room.players.values()].map(p=>({id:p.id,name:p.name,team:p.team,p:p.p,y:p.y,h:p.health,k:p.kills,d:p.deaths}));const msg={t:'snapshot',ts:Date.now(),players};for(const p of room.players.values())send(p.sock,msg)}},1000/30);
server.listen(PORT,'0.0.0.0',()=>console.log(`SHARDLINE server running on http://localhost:${PORT}`));
